GET http://localhost:3001/api/lambda HTTP/1.1
###
GET http://localhost:3001/api/lambda/1 HTTP/1.1


###
POST   http://localhost:3001/auth/login
Content-Type: application/json

{

    "email": "shalom@gmail.com",
    "password": "@!4"
}

### 
POST http://localhost:3001/email
Content-Type: application/json

{
    "name": "boobie",
    "email": "shalom@gmail.com",
    "message": "im here guys"
}

###
POST  http://localhost:3001/auth/login
Content-Type: application/json

{
    "email": "zivfromisrael@gmail.com",
    "password": "gggg"
}
###
GET  https://valid-cors.herokuapp.com/https://jobs.github.com/positions.json
Origin: "*"